### ISSUE TITLE
关于weighted_score的计算

### ISSUE THREAD

**Issue by DropYearning** [Albertsr/Anomaly-Detection#3]
https://github.com/Albertsr/Anomaly-Detection/blob/a48e3ed40539e3fd2026fb78463c696c396ccc21/SemiSupervised-ADOA/adoa.py#L85
ADOA算法实现中计算weighted_score的公式是`self.theta * isolation_score_scaled *  + (1-self.theta) * similarity_score_scaled`，按论文意思显然公式中的`*`是多余的。但是去除`*`后AUC反而大幅度下降，这是为什么？

**Comment by Albertsr** [comment]
是的，第二个乘号是多余的，谢谢指出；
“去除*后AUC反而大幅度下降”，不清楚你这边的具体情况，theta作为一个超参数，作者未给出设定的标准；我个人初步的想法是，可尝试运用贝叶斯优化进行寻优；

**Comment by DropYearning** [comment]
> 是的，第二个乘号是多余的，谢谢指出；
> “去除*后AUC反而大幅度下降”，不清楚你这边的具体情况，theta作为一个超参数，作者未给出设定的标准；我个人初步的想法是，可尝试运用贝叶斯优化进行寻优；

谢谢回复，关于更正后AUC性能下降的原因应该是超参数导致的，我会进一步探索。
非常感谢你复现的一系列异常检测代码！
