### ISSUE TITLE
adoa dont have total_score

### ISSUE THREAD

**Issue by wenyanghan** [Albertsr/Anomaly-Detection#5]
def determine_trainset(self):
        weighted_score = self.cal_weighted_score()
        min_score, max_score, median_score = [func(weighted_score) for func in (np.min, np.max, np.median)]
        anomalies_score = weighted_score[:len(self.anomalies)]
        unlabel_scores = weighted_score[len(self.anomalies):]
        
        self.alpha = np.mean(anomalies_score) if self.alpha == 'auto' else self.alpha
        #change total_score ?? but i canot find total_score
        self.beta = median_score if median_score < self.alpha else np.percentile(total_score, 45)
        assert self.beta < self.alpha, 'beta should be smaller than alpha.'

**Comment by Albertsr** [comment]
Please replace 'total_score' with 'weighted_score', it was careless of me; thank you for pointing out this omission
